### ISSUE TITLE
Puja Pandal API

### ISSUE THREAD

**Issue by TheHappyBaloney** [Pujo-Atlas-Kolkata/PujoAtlasKol-Backend#1]

**Comment by Sbasu2512** [comment]
Need more info, I can help out!!

**Comment by Andrew99xx** [comment]
list down all APIs

**Comment by Avinaba-Bhattacharjee** [comment]
I thought of the following:
1. /pujo/list/?q='' : lists all pujos in the city, can take search queries also as a parameter
2. /pujo/list/location/{:loc_id}?q='' : lists all pujos in a particular locality say, Behala, Gariahat, College Street, etc. Also, supports search queries 
3. /pujo/list/territory/{:terr_id}?q='' : lists all pujos in a particular territory say, North Kolkata, South Kolkata, etc. Also, supports search queries

Similar routes can be defined for nearby restaurants, police stations, hospitals, etc.

**Comment by pnaskardev** [comment]
`class Pandal(models.Model):
    name = models.CharField(max_length=100)
    lat = models.FloatField(null = True)
    lon = models.FloatField(null = True)
    address = models.TextField()
    zone = models.CharField(max_length=100)
    uuid = models.UUIDField()
    # TODO Images of the particular pandal

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name`
        
        
 THis is the model we have for list of Pandals please create APIs for this although I recommend first dockerizing and filling up the DB first
