### ISSUE TITLE
Implement password reset

### ISSUE THREAD

**Issue by Sbasu2512** [Pujo-Atlas-Kolkata/PujoAtlasKol-Backend#18]
Implement an api endpoint where user can reset their password. User can enter their username and email to verify themselves and upon successful verification, we let them reset their password.

(Forgot password feature)

**Comment by Sama-004** [comment]
@Sbasu2512 you can assign this to me. What should we use to send emails btw?

**Comment by Sbasu2512** [comment]
@Sama-004 for this issue, front end would have three inputs, username and email along with new password. we will check if username is present in database and then we check if the email matches to that user's email in db. then we update their password in the database.
