### ISSUE TITLE
Implement uploading of pictures

### ISSUE THREAD

**Issue by Sbasu2512** [Pujo-Atlas-Kolkata/PujoAtlasKol-Backend#19]
users can upload a picture which we will upload to a different storage partner and will get a url back, which we will store in the database.

**Comment by RudrasSingh** [comment]
hey! @Sbasu2512 
Can you assign me this issue!

**Comment by Sbasu2512** [comment]
Hey, @RudrasSingh 

Thank you for contacting us for contribution, but we are moving from django to node js. Hence we are closing this issue, please keep an eye on issues board to see new issue. Thanks :)
