### ISSUE TITLE
Implement Metro API

### ISSUE THREAD

**Issue by Sbasu2512** [Pujo-Atlas-Kolkata/PujoAtlasKol-Backend#58]
id
lat
lon
name
station_code
line
created_at
updated_at

line needs to be an array

**Comment by Sama-004** [comment]
you need lat and lon of the station right? also this needs to be done in js? I can work on this. Do we also need the schedule for the metro?

**Comment by Sbasu2512** [comment]
@Sama-004 hey please implement in typescript. Yes we need latitude and longitude for metro. You can start working on it. Thanks
